### PR TITLE
Feat PLA-6726 launch content with w kwebview

### PR DESCRIPTION
**Pull request by wojtiku**
… in WK WebView on iOS [PLA-6726]

### Issue link
https://pitcher-ag.atlassian.net/browse/PLA-6726

### 📖  Description
This pull request adds handling of the `useWKView` file metadata field to `openContent` so that impact ios uses WKWebView instead of UIWebView for a file.

This is a corresponding PR to https://github.com/PitcherAG/pitcher-js-platform/pull/141

### 📷  Screenshots
n/a

[PLA-6726]: https://pitcher-ag.atlassian.net/browse/PLA-6726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by AykutBurak — DISMISSED** [review]

**Comment by pegiadise** [comment]
> There are 5 commits that come from... I don't know where - I fetched from remote, rebased etc.. they are still showing up - anyone knows what this could be before I dive in?

Probably wrong base branch. I would just rebranch out from latest dev and cherrypick the latest commit

**Comment by wojtiku** [comment]
> > There are 5 commits that come from... I don't know where - I fetched from remote, rebased etc.. they are still showing up - anyone knows what this could be before I dive in?
> 
> Probably wrong base branch. I would just rebranch out from latest dev and cherrypick the latest commit

Exactly what I thought. So I did `git fetch` and rebased on top of `origin/dev` 🤷 


> I wonder if it could depend on your local git repo?
Maybe, but it fetched just fine.


I will fix it later. Just thought it is weird enough to share :)

**Review by kouts — DISMISSED** [review]

**Comment by wojtiku** [comment]
Ok, branch hard reset to origin/dev and the commit is reapplied as patch through Intellij. Looks good now.

**Review by pegiadise — APPROVED** [review]

**Review by AykutBurak — APPROVED** [review]

**Comment by wojtiku** [comment]
Force merging as people github is waiting for are no longer with the company.

**Pull request merged**
